"""Config file at ~/.config/dragoman/config.toml.

Resolution order for any value: env var > config file > caller default.
Env vars always win, so a one-shot export overrides a saved config without
editing the file.

For secret values (API keys), use `get_secret()` instead of `get_value()` —
it additionally resolves `op://...`, `keychain://...`, and `env:...`
references through `dragoman.secrets.resolve()`.
"""

import os
import tomllib
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

CONFIG_DIR = Path.home() / ".config" / "dragoman"
CONFIG_FILE = CONFIG_DIR / "config.toml"


def load_config() -> dict:
    """Load config from disk; return {} if no config file exists."""
    if not CONFIG_FILE.exists():
        return {}
    with open(CONFIG_FILE, "rb") as f:
        cfg = tomllib.load(f)
        
    # Migrate legacy singletons to the new dynamic provider registry
    providers = cfg.setdefault("providers", {})
    needs_save = False
    
    legacy_map = {
        "openai_compat": "openai_compat",
        "openai": "openai_compat",
        "perplexity": "openai_compat",
        "ollama": "openai_compat",
        "gemini": "gemini"
    }
    
    for legacy_key, internal_type in legacy_map.items():
        if legacy_key in cfg:
            block = cfg.pop(legacy_key)
            block["type"] = internal_type
            
            # Ollama natively didn't enforce a host sometimes, let's ensure it has one for openai_compat
            if legacy_key == "ollama" and "host" not in block:
                block["host"] = "http://localhost:11434/v1"
            elif legacy_key == "ollama" and not block.get("host", "").endswith("/v1"):
                block["host"] = block["host"].rstrip("/") + "/v1"
                
            providers[legacy_key] = block
            needs_save = True
            
    if needs_save:
        save_config(cfg)
        
    return cfg


def save_config(config: dict) -> None:
    """Write config to disk in TOML format. Creates the directory if missing."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# dragoman config — generated by `dragoman init`",
        "# https://github.com/asakin/dragoman",
        "",
    ]
    
    def _write_section(name: str, entries: dict):
        lines.append(f"[{name}]")
        for key, value in entries.items():
            if value is None or value == "":
                continue
            if isinstance(value, bool):
                lines.append(f"{key} = {'true' if value else 'false'}")
            elif isinstance(value, (int, float)):
                lines.append(f"{key} = {value}")
            elif isinstance(value, list):
                # Simple list of strings
                items = ", ".join(f'"{str(v).replace(chr(92), chr(92)*2).replace(chr(34), chr(92)+chr(34))}"' for v in value)
                lines.append(f"{key} = [{items}]")
            else:
                escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'{key} = "{escaped}"')
        lines.append("")

    for section, entries in config.items():
        if isinstance(entries, dict):
            # Check if it contains nested dicts (e.g. providers.groq)
            if any(isinstance(v, dict) for v in entries.values()):
                for subsection, subentries in entries.items():
                    if isinstance(subentries, dict):
                        _write_section(f"{section}.{subsection}", subentries)
            else:
                _write_section(section, entries)
                
    CONFIG_FILE.write_text("\n".join(lines))


def get_value(provider: str, key: str, env_var: Optional[str] = None) -> Optional[str]:
    """Resolve a non-secret config value with env-var override.

    Order: env var (if env_var given and set) > config[provider][key] > None.
    """
    if env_var:
        env_val = os.environ.get(env_var)
        if env_val:
            return env_val
    config = load_config()
    section = config.get(provider, {})
    val = section.get(key)
    return val if val else None


def get_secret(provider: str, key: str, env_var: Optional[str] = None) -> Optional[str]:
    """Same as get_value, but additionally resolves op://, keychain://, env:
    references through dragoman.secrets.

    Returns the literal key string, or None if not configured.
    """
    from dragoman import secrets

    raw = get_value(provider, key, env_var)
    return secrets.resolve(raw)


def normalize_host(host: str) -> Optional[str]:
    """Normalize a host string to a URL. Returns None if input doesn't look like one.

    - Empty/None → None
    - With scheme (http://..., https://...) → returned as-is
    - Without scheme but URL-shaped (e.g. "127.0.0.1:11435") → prepended with "http://"
    - Bare strings that don't look like a host (e.g. "LiteLLM", "skip") → None

    Keeps existing shell rcs working when they have `OLLAMA_HOST=127.0.0.1:11435`
    (no scheme), and rejects placeholder service names typed into `dragoman init`.
    """
    if not host:
        return None
    candidate = host if "://" in host else "http://" + host
    parsed = urlparse(candidate)
    if not parsed.scheme or not parsed.netloc:
        return None
    netloc = parsed.netloc
    if netloc != "localhost" and "." not in netloc and ":" not in netloc:
        return None
    return candidate
